import type { BlogPost } from '../../postTypes';
import heroImage from './hero-image.webp';
import cardImage from './card-image.webp';
import bodyImageOne from './body-image-1.webp';
import bodyImageTwo from './body-image-2.webp';
import bodyImageThree from './body-image-3.webp';
import bodyImageFour from './body-image-4.webp';

const post: BlogPost = {
  slug: 'straight-greats-5-rolling-stones-six-straight',
  title: 'Straight Greats No. 5: The Rolling Stones Had Six — and the Weird One Counts',
  excerpt:
    'The Rolling Stones made six straight great albums from Their Satanic Majesties Request through Goats Head Soup: five Certified, one On the Edge, and the weird one counts.',
  section: 'music-playlists',
  publishedAt: '2026-08-03',
  status: 'Recent',
  heroImage,
  heroAlt:
    'Straight Greats scorecard for the Rolling Stones’ six-album run, with five Certified albums and Goats Head Soup On the Edge.',
  cardImage,
  cardAlt:
    'A listener writes out the Rolling Stones’ six-album run beside a turntable and the records being judged.',
  bodyHtml: `
<h2>STRAIGHT GREATS</h2>
<h3>SIX STRAIGHT</h3>
<p>1 ON THE EDGE · 5 CERTIFIED</p>
<h3>THE ROLLING STONES</h3>
<p><em>Their Satanic Majesties Request (1967) · Beggars Banquet (1968) · Let It Bleed (1969) · Sticky Fingers (1971) · Exile on Main St. (1972) · Goats Head Soup (1973)</em></p>
<p>Straight Greats is the series for artists who put together runs of nearly perfect albums, one after another. Some make it to three. A few go further. The point isn't whether every sane person on earth has to agree. The point is that a run holds up start to finish, album after album, with no dead weight and no charity required.</p>
<p>If you're new, the scorecard is explained in <a href="https://ourolddad.com/post/how-the-straight-greats-scorecard-works">How the Straight Greats Scorecard Works</a>. Short version: Certified clears the line clean, On the Edge is a great album with a live argument attached, and a run only gets to carry one silver. All rulings use the original UK releases — original tracklists, original running orders, no deluxe editions, no bonus anything.</p>
<p>The Stones went six straight, and five of them are gold. To explain how I got there, I have to explain how I met these albums in the first place, because I didn't meet them when you'd think.</p>
<p>I graduated high school in 1983. When I started in '79, the whole history of the kind of rock I'm talking about was only about twenty years deep. That's it. And those twenty years were so packed, so urgent, every year building on the last one so fast, that a band from the sixties already felt ancient. The Stones, the Beatles, the Doors — old bands. Never mind that the Stones were still monsters right then, putting out Some Girls and Emotional Rescue and Tattoo You while I was walking the halls. The sixties stuff was history.</p>
<p>And the radio kept it that way. Album rock gave you a keyhole view of the giants — Satisfaction, Light My Fire, Stairway to Heaven, the same handful forever. You knew the songs. You didn't know the albums. To this day there are songs I love and hate at the same time because of it. Satisfaction sticks in my head and I don't even want it there. That's not the record's fault, that's repetition's fault, and it's exactly why this scorecard has a fresh-listen clause: skipping an overplayed great song is listener fatigue, not a defect in the album.</p>
<figure class="post-figure">
<img src="${bodyImageOne}" alt="A teenage listener in a cluttered late-seventies room discovers older Rolling Stones records through radio, vinyl, and cassettes." loading="lazy" decoding="async" />
</figure>
<p>The nineties is when it cracked open. I was older, buying my own albums, getting to shows on my own — Dead shows, plenty of acid, plenty of mushrooms, the whole deal. And CDs happened. Everything got reissued, boxed, remastered. The Zeppelin box did it to me first: holy fuck, I didn't know any of this existed. I bought all the albums individually on top of the box. Pink Floyd, same story. And somewhere in there I started buying the old Stones records, so a run made in the late sixties landed on me like new releases twenty-five years later. I played them constantly, which probably drove everyone around me crazy — nobody else wanted to go any deeper into the old bands than the radio ever went. Their loss. What blew me away wasn't that the famous songs were good. It's that the deep cuts were better.</p>
<p>Here's the shape of the run as I always heard it. They spent 1967 doodling around on Their Satanic Majesties Request, chasing somebody else's sound. Then they walked away from it — or got embarrassed by it, same result — and put out Beggars Banquet, and you can hear them realize it: holy fuck, we can do this other thing. Then they just blasted it out. Let It Bleed. Sticky Fingers. Exile on Main St.</p>
<p>And here's the punchline of this whole ruling: even the doodling clears the bar. We'll get there.</p>
<p>First, the middle four. I'm not going to write four reviews of what the whole world stipulated fifty years ago, but each one earned its badge, so each one gets its fingerprint. All four are Certified — there's no tier above gold on this scorecard — but I'll say up front how I rank them inside it. Beggars Banquet clears the line clean. The three after it clear it and then keep going, three albums that don't just stack bangers but fit together, play together, like one long record. Those three sit on my shortest list in rock history.</p>
<p>Beggars Banquet is where they found it, and it took me the longest to fully get. Here's the moment it opened up. Sometime in the nineties I was in Amsterdam, high as you'd expect, and the Hard Rock Cafe had the Rock and Roll Circus footage playing — this is before YouTube, before MTV would touch deep material like that, so you just never saw this stuff. And watching Sympathy for the Devil in that film, I heard the song for the first time. I'd only ever heard it at surface level on the radio. Now suddenly it was all layers, almost symphonic, and I realized how instrumentally great this band actually was. Go back to the record after that and it keeps paying: Stray Cat Blues might be the meanest thing on it — that bass crawling under the piano line — and Factory Girl and Salt of the Earth keep climbing on me with every play. Parachute Woman has never been a favorite, but every time I put it on again it holds its spot. Solid all the way through, and rising. Certified.</p>
<figure class="post-figure">
<img src="${bodyImageTwo}" alt="An adult listener in an Amsterdam room studies Rolling Stones CDs beside a canal window, map, and travel notes." loading="lazy" decoding="async" />
</figure>
<p>Let It Bleed opens with Gimme Shelter, which is one of the best songs ever recorded, full stop. I never saw the Stones live, but I saw Keith Richards perform it, and that counts for something in my house. And then the record just refuses to let up — Midnight Rambler, Monkey Man, Love in Vain — before closing on You Can't Always Get What You Want. Front to back, no excuses needed. Certified.</p>
<p>Sticky Fingers doesn't have a sour note on it. The funny thing is which songs I already knew: Brown Sugar and Wild Horses were everywhere growing up, and so was Bitch — surprisingly, given the name. What the radio never told me was the rest of it. Sway is better than anyone gives it credit for, Sister Morphine is the one I really love, and Moonlight Mile ambushed me completely — a hit I never knew existed, sitting at the end of a record I thought I already knew. Goes all the way through. Certified.</p>
<p>And Exile on Main St. is the best of all of them. It's a double fucking album and it barely wastes a minute. You know the front end — Rocks Off, Tumbling Dice, which I heard a thousand times and somehow never wore out. Then it goes down into the seams, and that's where it lives: Sweet Virginia, Torn and Frayed, Shine a Light, Soul Survivor. Even Turd on the Run and Ventilator Blues fit exactly where they sit. You listen to this thing and you can tell — these guys knew they were blowing everything away. Somebody's going to try the count on me here, so: eighteen tracks, and there's exactly one where I understand the argument — I Just Want to See His Face, which is more séance than song. But I don't reach for the button, and the Skip Test judges a double in proportion anyway. One arguable moment across eighteen tracks isn't a defect. Certified, and it wasn't close.</p>
<p>Nobody touches that middle four. Maybe three acts in history get close, and I'll fight about which three in another post.</p>
<p>Now the record everybody expects me to wave off — and the hardest ruling on the board.</p>
<p>I bought Their Satanic Majesties Request last, partly because of the cover. Look at it honestly: it's idiotic. And here's the difference. Sgt. Pepper was glammy before glam existed, and yeah, a little weird — but the Beatles were obviously making something that was theirs. The Stones, dressed up like wizards, look like they're faking it. You can see them reaching for something, and whatever it was, it wasn't them, and it didn't work. It looked dumb even for its time — especially knowing what was about to come out of these same guys a year later. What the hell were they wasting their time on? I figured the record had to be a farce. Then it caught me at exactly the right time. I was tripping a lot in those years, and this album got played through more of that than any record has a right to, which means it changed my DNA. I'm pretty sure I heard on Joe Rogan that that's how that works.</p>
<p>And here's the thing: under all the bullshit they layered on top — the ultra-trippy production, the trying to be somebody they weren't — they couldn't hold back what they were onto. It was almost too powerful, and it leaks out everywhere. Citadel is a rock song wearing a costume. 2000 Man. 2000 Light Years from Home still sounds like a transmission from somewhere cold. She's a Rainbow is so pretty it almost doesn't seem like it was supposed to be on there. The record's reputation got wrecked twice — once by its own pictures, and once by the monster run that came right after it, which recast it forever as the embarrassing detour. Same rule both directions: you rate the album, not its neighbors. Goats Head doesn't get docked for following Exile, and Satanic Majesties doesn't get docked for being the weird one before Beggars. On its own terms, they did better here than they ever get credit for.</p>
<p>I struggled with this one, and I'll admit two things straight out. One: my DNA may have been changed. I can't fully un-hear the nineties. Two: what carries the fringe tracks for me is the mood of the whole thing — the record works as one big trip, and inside that mood I never reach for the button, not even on the eight-minute reprise of Sing This All Together that closes side one. It's a big trippy song at the end of a big trippy side, and it fits where it sits. But I can see exactly where that reprise knocks the record off for somebody else. If you make it a silver, that's a fair ruling and I won't act like you're crazy. The Skip Test just doesn't ask how the album got into you. It asks whether you skip, and I don't. Zero. Certified.</p>
<figure class="post-figure">
<img src="${bodyImageThree}" alt="A turntable releases a surreal psychedelic dreamscape of flowers, planets, carnival tents, and distant towers." loading="lazy" decoding="async" />
</figure>
<p>Goats Head Soup is the silver, and it's the opposite problem. No costume, no farce. I wanted it so badly to be the other ones that it felt like a letdown the first time through. It isn't a letdown. I went back through it fresh for this ruling expecting the weak spots to show up early, and they never came — Heartbreaker is fucking amazing, Angie, 100 Years Ago, and the record is solid deep into side two. Then Winter and Can You Hear the Music arrive back to back, and they just don't fit the mood of the record enough to make it. I can even see why they close the album the way they do — Star Star is great and lands the ending. But my hand drifts on those two, and two skips is two skips.</p>
<p>I did ask myself whether I was really docking this record for having to follow Let It Bleed, Sticky Fingers, and Exile. Same rule as above, and it's not what's happening. The two skips are real on their own terms. Neither one carries structural weight, so the record stays great and stays silver. On the Edge.</p>
<p>And the run really does end where I say it ends, on both sides. Here's why.</p>
<p>Before it sits Between the Buttons, and under the UK rule it isn't close. Remember, the UK version doesn't have Let's Spend the Night Together or Ruby Tuesday on it — those were the American pressing. Without those two, how is this record even contending? What's left has some great stuff on it, sitting right next to stuff that wasn't quite ready yet and stuff that was already past due. You can feel what this band is about to become, and you can also hear them still finishing up being what they used to be. I take it off before it ends. Even with the two American singles bolted back on, it'd be closer, not close.</p>
<p>After the run comes It's Only Rock 'n Roll, and that one hurts more to cut. So let me do it by naming what works instead: the title track, which got played to death and survived it. Ain't Too Proud to Beg. Dance Little Sister. Time Waits for No One. All decent or better. The rest of it sounds like sequels — part twos of songs that already worked somewhere else, except the thing that made them work didn't come along. And that's the tell. I'll sit through all eighteen tracks of Exile. I would not sit through this one the same way. It doesn't make it.</p>
<p>So here's the ruling. The two records at the ends of the run were the fight, and I came out of it convinced they equal one gold and one silver — not two silvers. Six straight: five gold, plus the one silver a run is allowed to carry, spent on the last record. Goats Head Soup is the only thing standing between the Stones and a perfect six, and it earned its silver honestly. Six is as long as this series has gone, and I don't expect many more to get there.</p>
<figure class="post-figure">
<img src="${bodyImageFour}" alt="Six Rolling Stones album sketches are arranged in a row beside a turntable, notebook, and headphones as the run is judged." loading="lazy" decoding="async" />
</figure>
<p>If you think Satanic Majesties doesn't belong, don't send me &quot;come on, be serious.&quot; Name the track. Tell me which one makes you reach for the button, and I'll listen to it again and tell you why I don't. The badge that moves is the one somebody argues.</p>
<p>The Rolling Stones are welcome to <a href="https://ourolddad.com/contact">fill out the contact form</a> to claim the badge.</p>
<p>Where does the Stones run start and stop for you? <a href="https://ourolddad.com/contact">Let us know through the contact page</a>.</p>
<h2>Hear the Run</h2>
<p><a href="https://www.youtube.com/playlist?list=PLaDEfwnZOj_c" target="_blank" rel="noreferrer">Watch on YouTube</a></p>
<p><a href="https://music.youtube.com/playlist?list=PLaDEfwnZOj_c&amp;si=DN-qh2u7Qe-QwEyP" target="_blank" rel="noreferrer">Listen on YouTube Music</a></p>
<div class="post-links">
<a class="button button--primary" href="https://www.youtube.com/watch?list=PLaDEfwnZOj_c" target="_blank" rel="noreferrer">Watch on YouTube</a>
<a class="button button--ghost" href="https://music.youtube.com/playlist?list=PLaDEfwnZOj_c&amp;si=DN-qh2u7Qe-QwEyP" target="_blank" rel="noreferrer">Listen on YouTube Music</a>
</div>
  `,
};

export default post;
